package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/valllabh/security-cli/graph/model"
)

// AddPackage is the resolver for the addPackage field.
func (r *mutationResolver) AddPackage(ctx context.Context, input []*model.AddPackageInput) (*model.AddPackagePayload, error) {
	panic(fmt.Errorf("not implemented: AddPackage - addPackage"))
}

// UpdatePackage is the resolver for the updatePackage field.
func (r *mutationResolver) UpdatePackage(ctx context.Context, input model.UpdatePackageInput) (*model.UpdatePackagePayload, error) {
	panic(fmt.Errorf("not implemented: UpdatePackage - updatePackage"))
}

// DeletePackage is the resolver for the deletePackage field.
func (r *mutationResolver) DeletePackage(ctx context.Context, filter model.PackageFilter) (*model.DeletePackagePayload, error) {
	panic(fmt.Errorf("not implemented: DeletePackage - deletePackage"))
}

// AddLicense is the resolver for the addLicense field.
func (r *mutationResolver) AddLicense(ctx context.Context, input []*model.AddLicenseInput, upsert *bool) (*model.AddLicensePayload, error) {
	panic(fmt.Errorf("not implemented: AddLicense - addLicense"))
}

// DeleteLicense is the resolver for the deleteLicense field.
func (r *mutationResolver) DeleteLicense(ctx context.Context, filter model.LicenseFilter) (*model.DeleteLicensePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteLicense - deleteLicense"))
}

// AddPackageVersion is the resolver for the addPackageVersion field.
func (r *mutationResolver) AddPackageVersion(ctx context.Context, input []*model.AddPackageVersionInput, upsert *bool) (*model.AddPackageVersionPayload, error) {
	panic(fmt.Errorf("not implemented: AddPackageVersion - addPackageVersion"))
}

// DeletePackageVersion is the resolver for the deletePackageVersion field.
func (r *mutationResolver) DeletePackageVersion(ctx context.Context, filter model.PackageVersionFilter) (*model.DeletePackageVersionPayload, error) {
	panic(fmt.Errorf("not implemented: DeletePackageVersion - deletePackageVersion"))
}

// AddProgrammingLanguage is the resolver for the addProgrammingLanguage field.
func (r *mutationResolver) AddProgrammingLanguage(ctx context.Context, input []*model.AddProgrammingLanguageInput, upsert *bool) (*model.AddProgrammingLanguagePayload, error) {
	panic(fmt.Errorf("not implemented: AddProgrammingLanguage - addProgrammingLanguage"))
}

// DeleteProgrammingLanguage is the resolver for the deleteProgrammingLanguage field.
func (r *mutationResolver) DeleteProgrammingLanguage(ctx context.Context, filter model.ProgrammingLanguageFilter) (*model.DeleteProgrammingLanguagePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteProgrammingLanguage - deleteProgrammingLanguage"))
}

// AddPackageType is the resolver for the addPackageType field.
func (r *mutationResolver) AddPackageType(ctx context.Context, input []*model.AddPackageTypeInput, upsert *bool) (*model.AddPackageTypePayload, error) {
	panic(fmt.Errorf("not implemented: AddPackageType - addPackageType"))
}

// DeletePackageType is the resolver for the deletePackageType field.
func (r *mutationResolver) DeletePackageType(ctx context.Context, filter model.PackageTypeFilter) (*model.DeletePackageTypePayload, error) {
	panic(fmt.Errorf("not implemented: DeletePackageType - deletePackageType"))
}

// QueryPackage is the resolver for the queryPackage field.
func (r *queryResolver) QueryPackage(ctx context.Context, filter *model.PackageFilter, order *model.PackageOrder, first *int, offset *int) ([]*model.Package, error) {
	panic(fmt.Errorf("not implemented: QueryPackage - queryPackage"))
}

// AggregatePackage is the resolver for the aggregatePackage field.
func (r *queryResolver) AggregatePackage(ctx context.Context, filter *model.PackageFilter) (*model.PackageAggregateResult, error) {
	panic(fmt.Errorf("not implemented: AggregatePackage - aggregatePackage"))
}

// GetLicense is the resolver for the getLicense field.
func (r *queryResolver) GetLicense(ctx context.Context, id string) (*model.License, error) {
	panic(fmt.Errorf("not implemented: GetLicense - getLicense"))
}

// QueryLicense is the resolver for the queryLicense field.
func (r *queryResolver) QueryLicense(ctx context.Context, filter *model.LicenseFilter, order *model.LicenseOrder, first *int, offset *int) ([]*model.License, error) {
	panic(fmt.Errorf("not implemented: QueryLicense - queryLicense"))
}

// AggregateLicense is the resolver for the aggregateLicense field.
func (r *queryResolver) AggregateLicense(ctx context.Context, filter *model.LicenseFilter) (*model.LicenseAggregateResult, error) {
	panic(fmt.Errorf("not implemented: AggregateLicense - aggregateLicense"))
}

// GetPackageVersion is the resolver for the getPackageVersion field.
func (r *queryResolver) GetPackageVersion(ctx context.Context, id string) (*model.PackageVersion, error) {
	panic(fmt.Errorf("not implemented: GetPackageVersion - getPackageVersion"))
}

// QueryPackageVersion is the resolver for the queryPackageVersion field.
func (r *queryResolver) QueryPackageVersion(ctx context.Context, filter *model.PackageVersionFilter, order *model.PackageVersionOrder, first *int, offset *int) ([]*model.PackageVersion, error) {
	panic(fmt.Errorf("not implemented: QueryPackageVersion - queryPackageVersion"))
}

// AggregatePackageVersion is the resolver for the aggregatePackageVersion field.
func (r *queryResolver) AggregatePackageVersion(ctx context.Context, filter *model.PackageVersionFilter) (*model.PackageVersionAggregateResult, error) {
	panic(fmt.Errorf("not implemented: AggregatePackageVersion - aggregatePackageVersion"))
}

// GetProgrammingLanguage is the resolver for the getProgrammingLanguage field.
func (r *queryResolver) GetProgrammingLanguage(ctx context.Context, id string) (*model.ProgrammingLanguage, error) {
	panic(fmt.Errorf("not implemented: GetProgrammingLanguage - getProgrammingLanguage"))
}

// QueryProgrammingLanguage is the resolver for the queryProgrammingLanguage field.
func (r *queryResolver) QueryProgrammingLanguage(ctx context.Context, filter *model.ProgrammingLanguageFilter, order *model.ProgrammingLanguageOrder, first *int, offset *int) ([]*model.ProgrammingLanguage, error) {
	panic(fmt.Errorf("not implemented: QueryProgrammingLanguage - queryProgrammingLanguage"))
}

// AggregateProgrammingLanguage is the resolver for the aggregateProgrammingLanguage field.
func (r *queryResolver) AggregateProgrammingLanguage(ctx context.Context, filter *model.ProgrammingLanguageFilter) (*model.ProgrammingLanguageAggregateResult, error) {
	panic(fmt.Errorf("not implemented: AggregateProgrammingLanguage - aggregateProgrammingLanguage"))
}

// GetPackageType is the resolver for the getPackageType field.
func (r *queryResolver) GetPackageType(ctx context.Context, id string) (*model.PackageType, error) {
	panic(fmt.Errorf("not implemented: GetPackageType - getPackageType"))
}

// QueryPackageType is the resolver for the queryPackageType field.
func (r *queryResolver) QueryPackageType(ctx context.Context, filter *model.PackageTypeFilter, order *model.PackageTypeOrder, first *int, offset *int) ([]*model.PackageType, error) {
	panic(fmt.Errorf("not implemented: QueryPackageType - queryPackageType"))
}

// AggregatePackageType is the resolver for the aggregatePackageType field.
func (r *queryResolver) AggregatePackageType(ctx context.Context, filter *model.PackageTypeFilter) (*model.PackageTypeAggregateResult, error) {
	panic(fmt.Errorf("not implemented: AggregatePackageType - aggregatePackageType"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
